### ISSUE TITLE
hca prints --help insted of run

### ISSUE THREAD

**Issue by oskotsky** [HumanCellAtlas/dcp-cli#112]
hca dss download --bundle-uuid XXXXXXXXXX --replica aws just prints help output. adding --log-level DEBUG is not recognized as a switch 

Thank you

**Comment by ttung** [comment]
What do you get when you run `hca --version`?

**Comment by oskotsky** [comment]
$ hca --version
hca 3.4.6 (CPython 3.4.2 Linux-3.10.0-862.el7.x86_64-x86_64-with-redhat-7.5-Maipo)

I am trying to run this on rhel7 remote server, no gui. Would it be a problem? Does hca use port 443 only? I wonder if any additional traffic blocked by our firewall and that is why it breaks. 
Thank you

**Comment by ttung** [comment]
What's the exact command you're running?

**Comment by oskotsky** [comment]
I was given a script "hca-download-census". Inside the script this seems to fail: "hca dss download --bundle-uuid XXXXXXXXXX --replica aws". I tried on my home system - Ubuntu Desktop and it worked without any issues.

**Comment by ttung** [comment]
That looks good.  Can you zip up the contents of `~/.config/hca` and post that here?

**Comment by oskotsky** [comment]
[hca_config.zip](https://github.com/HumanCellAtlas/dcp-cli/files/1953407/hca_config.zip)
here it is

Thank you

**Comment by ttung** [comment]
Hm... that looks okay.  What do you get when you run `hca dss download --help`?

**Comment by oskotsky** [comment]
i see this:

$ hca dss download --help
usage: hca dss download [-h] --bundle-uuid BUNDLE_UUID --replica REPLICA
                        [--version VERSION] [--dest-name DEST_NAME]

Download a bundle and save it to the local filesystem as a directory.

optional arguments:
  -h, --help            show this help message and exit
  --bundle-uuid BUNDLE_UUID
  --replica REPLICA
  --version VERSION
  --dest-name DEST_NAME

**Comment by ttung** [comment]
So what do you get when you run:

`hca dss download --bundle-uuid c94a43f9-257f-4cd0-b2fe-eaf6d5d37d18 --replica aws`?

**Comment by oskotsky** [comment]
this is what is odd:

$ hca dss download --bundle-uuid c94a43f9-257f-4cd0-b2fe-eaf6d5d37d18 --replica aws
usage: hca dss [-h]
               {delete-subscription,post-search,get-file,put-subscription,post-bundles-checkout,get-subscriptions,put-bundle,head-file,get-bundles-checkout,delete-bundle,put-file,get-bundle,get-subscription,login,logout,download,upload}
               ...

positional arguments:
  {delete-subscription,post-search,get-file,put-subscription,post-bundles-checkout,get-subscriptions,put-bundle,head-file,get-bundles-checkout,delete-bundle,put-file,get-bundle,get-subscription,login,logout,download,upload}
    delete-subscription
                        Delete an event subscription.
    post-search         Find bundles by searching their metadata with an
                        Elasticsearch query
    get-file            Retrieve a file given a UUID and optionally a version.
    put-subscription    Create a event subscription.
    post-bundles-checkout
                        Check out a bundle to DSS-managed or user-managed
                        cloud object storage destination
    get-subscriptions   Retrieve a user\'s event subscriptions.
    put-bundle          Create a bundle
    head-file           Retrieve a file's metadata given an UUID and
                        optionally a version.
    get-bundles-checkout
                        Check the status of a checkout request.
    delete-bundle       Delete a bundle or a specific bundle version
    put-file            Create a new version of a file
    get-bundle          Retrieve a bundle given a UUID and optionally a
                        version.
    get-subscription    Retrieve an event subscription given a UUID.
    login               Configure and save hca dss authentication credentials.
    logout              Clear hca dss authentication credentials previously
                        configured with ``hca dss login``.
    download            Download a bundle and save it to the local filesystem
                        as a directory.
    upload              Upload a directory of files from the local filesystem
                        and create a bundle containing the uploaded files.

optional arguments:
  -h, --help            show this help message and exit

**Comment by ttung** [comment]
Can you update your Python to a newer version?

**Comment by oskotsky** [comment]
this is a big system used by many people - it can't be done quickly and easily. :(

**Comment by oskotsky** [comment]
we have 2.7 and 3.4

**Comment by ttung** [comment]
Which 2.7 version?

**Comment by oskotsky** [comment]
Python 2.7.5

works the same way unfortunately:

$ export PATH=/opt/rh/python27/root/usr/bin/:$PATH
$ python --version
Python 2.7.5
$ 
$ hca dss download --bundle-uuid c94a43f9-257f-4cd0-b2fe-eaf6d5d37d18 --replica aws
usage: hca dss [-h]
               {head-file,get-bundle,put-subscription,post-bundles-checkout,get-bundles-checkout,delete-subscription,put-file,get-file,delete-bundle,get-subscription,get-subscriptions,post-search,put-bundle,login,logout,download,upload}
               ...

positional arguments:
  {head-file,get-bundle,put-subscription,post-bundles-checkout,get-bundles-checkout,delete-subscription,put-file,get-file,delete-bundle,get-subscription,get-subscriptions,post-search,put-bundle,login,logout,download,upload}
    head-file           Retrieve a file's metadata given an UUID and
                        optionally a version.
    get-bundle          Retrieve a bundle given a UUID and optionally a
                        version.
    put-subscription    Create a event subscription.
    post-bundles-checkout
                        Check out a bundle to DSS-managed or user-managed
                        cloud object storage destination
    get-bundles-checkout
                        Check the status of a checkout request.
    delete-subscription
                        Delete an event subscription.
    put-file            Create a new version of a file
    get-file            Retrieve a file given a UUID and optionally a version.
    delete-bundle       Delete a bundle or a specific bundle version
    get-subscription    Retrieve an event subscription given a UUID.
    get-subscriptions   Retrieve a user\'s event subscriptions.
    post-search         Find bundles by searching their metadata with an
                        Elasticsearch query
    put-bundle          Create a bundle
    login               Configure and save hca dss authentication credentials.
    logout              Clear hca dss authentication credentials previously
                        configured with ``hca dss login``.
    download            Download a bundle and save it to the local filesystem
                        as a directory.
    upload              Upload a directory of files from the local filesystem
                        and create a bundle containing the uploaded files.

optional arguments:
  -h, --help            show this help message and exit
$

**Comment by kislyuk** [comment]
Hi @oskotsky, I recognize where the bug is coming from and push out a fix shortly. The issue has been fixed in Python 2.7, but, just putting Python 2.7 into your $PATH is not sufficient to trigger its use - you actually have to use `pip2` or a virtualenv to re-install the package.

**Comment by oskotsky** [comment]
Thank you! Running in virtualenv solved the problem. It should be encouraged anyway, right?

**Comment by oskotsky** [comment]
@kislyuk pointed the solution - running hca in virtualenv. solves the problem. Thank you so much!

**Comment by kozbo** [comment]
Closing
