### ISSUE TITLE
/version endpoint to retrieve current version

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/dcp-cli#113]
# User story
As a user of the DCP CLI/API I would like to know what version I am using by visiting the endpoint /version, and should return the answer in JSON format (like example below)

# DoD:
api.com/version 
returns JSON that contains the current version of the data-store CLI/API.

# Notes
_What version of each DCP service is currently deployed in staging?_ 

This question is not currently easy to answer, unless you visit this config file, which is manually curated afaik. https://github.com/HumanCellAtlas/dcp/blob/staging/components.yml

Recently, Green box added a [/version endpoint](http://pipelines.dev.data.humancellatlas.org/version) to Lira so we can see the version of all its dependencies quickly when we are in each deployment. 

```
{
  "cromwell_tools_version": "0.3.1",
  "launch_time": "2018-04-24 20:27:52 +00:00",
  "lira_version": "v0.9.1",
  "run_mode": "live_run",
  "submit_wdl_version": "v0.16.0",
  "workflow_info": {
    "Adapter10xCount": {
      "subscription_id": "placeholder-10x",
      "version": "10x_v0.1.0"
    },
    "AdapterSmartSeq2SingleCell": {
      "subscription_id": "placeholder-ss2",
      "version": "smartseq2_v0.4.0"
    }
  }
}
```

A quick way to answer the question at hand could be to add a /version endpoint to the DCP CLI so we can see all the versions that are deployed in that environment.

**Comment by mweiden** [comment]
We will probably want to just use the version in the service model (swagger file).

**Comment by sampierson** [comment]
@mweiden Do you mean that the CLI should use the version in the downloaded swagger file (which currenty only happens for DSS), or that the /version endpoint in the API should use the version in the swagger file?

**Comment by mweiden** [comment]
@sampierson (previous comment was @kislyuk on my computer, doing my best to represent): the CLI should use the version in the downloaded swagger file. There are certainly arguments for having a `GET /version` endpoint as well. If this is the case, the version returned by the endpoint and the version returned in the `swagger.json` should be the same.

**Comment by sampierson** [comment]
You miss my point.  The DCP is not just the DSS.  There are other components.  The only service for which the CLI downloads the swagger spec is the DSS (and IMO this leads to a clunky UX - downloading one swagger.json on every execution already makes the CLI start very slowly, downloading 4 would create a terrible UX).   Other components, Upload, Ingest and Green Box, **will** implement CLI commands, may not even have a downloadable swagger.json, and may choose not to implement their API via metaprogramming as the DSS has done.

**Comment by mweiden** [comment]
@sampierson `GET /version` is fine with me, just clarifying @kislyuk's message and the tradeoffs between each. It's true that `GET /version` is a more standardize format.

Here are a couple more points of clarification
* Re. the DCP having more components than just the DSS: understood; also it is possible to configure HTTP paths and JSON parsing rules for each to retrieve the version
* Re. the swagger download: I believe this file is cached, so it should only download once per component that uses the `SwaggerClient` until a refresh is needed (https://github.com/HumanCellAtlas/dcp-cli/issues/79)

**Comment by mweiden** [comment]
@sampierson Sorry, this got scrambled. I was trying to relay @kislyuk's earlier idea (it is DSS centric, but is not impossible to reconcile if you allow for configurable paths and JSON parsing to retrieve the version string per component).

Re. the swagger.json download: I believe this file is cached, so it should only download once per component that uses the `SwaggerClient` until a refresh is needed (https://github.com/HumanCellAtlas/dcp-cli/issues/79)

**Comment by kislyuk** [comment]
@sampierson Sorry about the abbreviated nature of my comment. Here is the expanded version.

The best practice for modern APIs is to provide a mechanism for API discovery and introspection. In the DSS API, we have been doing this by using the OpenAPI/Swagger standard. I think other DCP services should also provide Swagger-based API definitions (service models). It is natural to provide the API and service version as part of that introspection endpoint.

There are multiple ways to avoid the "clunky"/"terrible" UX that you describe. First, if preserve the contents of your home directory when you run the CLI, it will cache the API service model. Second, we can also ship the API definition with the package (allowing it to re-fetch the definition periodically when it's judged to be out of date).

Metaprogramming should not be confused with the rest of this issue, as it's really about API introspection. I agree that metaprogramming as a client design choice does not necessarily always make sense (I will however point out that it's a more scalable way to build API tooling).
