### ISSUE TITLE
Preview download very slow

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-cli#115]
Dear human cell atlas members,

I’m currently trying to download raw single-cell data from Melanoma Infiltration of stroll and immune Cells.
https://preview.data.humancellatlas.org

The download is very slow (less than 800 cells downloaded since 4 days….) and seems to be blocked now.

Do you have any idea why?
Can I have acess to these data via another download method?

Thank you very much fo your help
---------

Thank you very much for your answer.
1- Mac OS High Sierra (10.13.4)
2- My network speed is high but I’m below a proxy (Insitut Curie). Maybe it can explain the issue.
3- hca 3.4.6 (CPython 2.7.13 Darwin-17.5.0-x86_64-i386-64bit)

---------
Thank you for the details. We previously observed a related problem of 'normal' download speeds (50Mbps-150Mbps) for some time, but then at some point reduced down to ~100kbps for many hours indicating a timeout configuration problem.

Can you tell us whether you see this behavior, or whether you are observing constant low download speeds from the start of running the download script?

---------
I have tried with virtualenv but unfortunately, it doesn’t change anything…
I have only downloaded 1328 files among 6400 in 1 week…
Do you have another solution?

**Comment by ttung** [comment]
The earlier version of the HCA tool did not configure timeout correctly. I would recommend upgrading the HCA package (pip install --upgrade hca) and trying again.

**Comment by ttung** [comment]
Also, #101 would help out a lot here.

**Comment by kozbo** [comment]
This may be fixed. End user issue was narrowed down to show that their network was the issue. closing
