### ISSUE TITLE
"--replica gcp" not recognized when uploading bundle

### ISSUE THREAD

**Issue by melissachang** [HumanCellAtlas/dcp-cli#121]
```
~/data-store (master): hca dss upload --replica gcp --staging-bucket melchang-dss-bucket --src-dir data-bundle-examples/smartseq2/paired_ends
INFO:hca:Uploading 5 files from data-bundle-examples/smartseq2/paired_ends to melchang-dss-bucket
<snip>
  File "/usr/local/google/home/melchang/virtualenv/data-store/lib/python3.6/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/google/home/melchang/virtualenv/data-store/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/google/home/melchang/virtualenv/data-store/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
```
From the stack trace, looks like it's trying to upload to S3.

**Comment by sampierson** [comment]
Hi Melissa,
The upload service does not support the --replica flag.   All files are uploaded to AWS.
The fact that the command accepts that switch is a bug.  I suspect that some of the dss code is leaking out of it's area.  The "hca dss" commands do support the --replica option.

**Comment by melissachang** [comment]
I ran "hca dss upload". (I'm new to this, I wasn't sure if I wanted "hca upload" or "hca dss upload".)

**Comment by sampierson** [comment]
Use `hca upload`commands  if you are trying to stage files as part of a submission to the HCA Ingest system.
Use `hca dss upload` if you are trying to do something fancy with the Data-Store.

**Comment by melissachang** [comment]
Thanks. I think I want the latter. I'm trying to better understand Blue Box and Orange Box.

Feel free to close as WAI if you don't intend for `hca dss upload` to support gcp. (Though it would be nice if it gave an error instead of try to upload to S3.)
