### ISSUE TITLE
Add cli command to download files specified in manifest file constructed by the data browser

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp-cli#123]
The Data Browser facet search will construct a manifest file specifying UUIDs and timestamps for files the user wants to download.
We need to provide a "hca download <manifest_file>" cli command to do the actual download (including retries).

**Comment by kozbo** [comment]
Note that there has been a lot of discussion about the manifest file being human readable. This interface should produce a file format that is usable by non-programmers, perhaps outputting as a tsv or a csv file.  We could optionally save it in a machine readable format like JSON as well, or have optional output formats. But the requirement is that the user should be able to output a human readable format too.
