### ISSUE TITLE
Download fails with 0-byte files

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/dcp-cli#132]
# Steps to reproduce

1. Upload a 0-byte file.
2. Attempt to download it

**Comment by kozbo** [comment]
@ttung  please clarify with a test case?

**Comment by mweiden** [comment]
Closing - not enough information to reproduce

**Comment by ttung** [comment]
1. Upload a 0-byte file.
2. Attempt to download it.  Not sure what more information is needed.

**Comment by ttung** [comment]
Are you sure?  Did you actually try this?  IIRC, this fails because a [http ranged GET](https://github.com/HumanCellAtlas/dcp-cli/blob/aa811490d3c680018f6c1abeef3292098556b0ea/hca/dss/__init__.py#L122) fails when one does 0- on a 0-byte file.

**Comment by calvinnhieu** [comment]
I see. I did not try downloading a bundle.

I uploaded a file and performed a GET to "download" it. I'll look into downloading a bundle that contains a 0-byte file.
