### ISSUE TITLE
Request to add whitelisted domains to HCA Documentation Page

### ISSUE THREAD

**Issue by ogparra** [HumanCellAtlas/dcp-cli#133]
On the HCA Documentation page, a user has to click on a link to open a file with the list of whitelisted domains. We should include the whitelisted domains to the HCA docs http://hca.readthedocs.io/en/latest/  removing the need to click on the link.

**Comment by kislyuk** [comment]
Which list of domains are you referring to?

**Comment by kozbo** [comment]
We should remove the reference to the white listed domains. They should  not be in the public facing documentation. We should separate the upload docs from the consumer docs.

**Comment by mweiden** [comment]
As discussed, we won't be doing this
