### ISSUE TITLE
Improve code coverage of upload service client

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/dcp-cli#137]
https://codecov.io/github/HumanCellAtlas/dcp-cli?branch=master shows that the upload service has poor coverage. Let's find out if that is really true, and add tests if necessary.

**Comment by calvinnhieu** [comment]
@Bento007 and I inadvertently fixed this [here](https://github.com/HumanCellAtlas/dcp-cli/pull/143#issuecomment-408963141). Basically, codecov was only reporting coverage for one of the `coverage` statements run during `make test`. This is further verified by matching the timelines of [Matt's link](https://codecov.io/github/HumanCellAtlas/dcp-cli?branch=master) and [this commit](https://github.com/HumanCellAtlas/dcp-cli/commit/5d67fd69b7696576f90fd36372103a44a5777fd9#diff-b67911656ef5d18c4ae36cb6741b7965) on June 17. What is unclear, however, is why the date that code coverage dropped (June 14) matches with the above commit's [parent commit](https://github.com/HumanCellAtlas/dcp-cli/commit/3a8212bc20f1d948d8434a5b86707e647df3e1f9).

Either way, ready to close this issue unless we still think coverage needs to be improved.

**Comment by mweiden** [comment]
@calvinnhieu thanks, Calvin!
