### ISSUE TITLE
dcp cli should use the constants defined in dcplib

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/dcp-cli#149]
defined: https://github.com/HumanCellAtlas/dcplib/blob/1eb7032d01f6ac36b55c1bf3096d325978b026f2/dcplib/s3_multipart.py

currently should replace constants in https://github.com/HumanCellAtlas/dcp-cli/blob/aa5c7b6723ca01b9c9a7c723363966de9c31241b/hca/dss/upload_to_cloud.py and https://github.com/HumanCellAtlas/dcp-cli/blob/ed13906c2fa233184bd05b963f3ede2c200a9666/hca/upload/s3_agent.py

**Comment by ttung** [comment]
@mweiden can you make sure this gets addressed?

**Comment by mweiden** [comment]
@ttung sure

**Comment by sampierson** [comment]
I have a PR open that addresses the Upload part of this
https://github.com/HumanCellAtlas/dcp-cli/pull/147
