### ISSUE TITLE
Read The Docs TOC is duplicated

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-cli#179]
The formatting of the left hand TOC is inconsistent and has duplicated sections

see [docs](https://hca.readthedocs.io/en/latest/api.html)

![Screen Shot 2018-08-31 at 9.28.07 AM.png](https://images.zenhubusercontent.com/5a663ecd4b5806bc2bc3cc9c/7dbc8b1a-e1d8-4479-929c-b614481d8454)

**Comment by Bento007** [comment]
#196 fixes this
