### ISSUE TITLE
CLI help often lists required parameters as `optional`

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-cli#180]
I have come across several instances where the `--replica` is listed as optional, but is actually required. I suspect that the problem is systemic. There are other parameters that are in the wrong category besides  `--replica`.

     hca dss download_manifest --help  
shows
    optional arguments:
   -h, --help            show this help message and exit
   --manifest MANIFEST
   --replica REPLICA
   --initial-retries-left INITIAL_RETRIES_LEFT
   --min-delay-seconds MIN_DELAY_SECONDS
But both `--manifest` and `--replica` are required

**Comment by Bento007** [comment]
since we use argparse and flags for all parameters they will by design show up in optional arguments https://stackoverflow.com/questions/24180527/argparse-required-arguments-listed-under-optional-arguments
