### ISSUE TITLE
Remove the dependency on the retrying module

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/dcp-cli#194]
The `retrying` module, introduced in https://github.com/HumanCellAtlas/dcp-cli/commit/82cc38541c35d189b928cae54c1c603a3c0c8830, is unsupported, with the last release in 2016. We could consider replacing it with tenacity (https://github.com/jd/tenacity), but my suggestion is to configure retry logic in our HTTP client (requests/urllib3) instead.

**Comment by parthshahva** [comment]
Switched to tenacity
