### ISSUE TITLE
hca dss get-file output to console can corrupt console

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-cli#201]
First timer users won't know that the output will go to the console, and the result can be a corrupted console if they got a binary file and it printed to the console.

Suggested solution: inform user that cli users will get output on stdout

-- old comments below
as a user I would like to have an example of how to use a command to reduce the occurrence of surprises and mistakes.

Example: 
The `hca dss get-file ...` command help does not specify that it dumps the file to stdout. If the user chooses to download a binary file they will be surprised by the output.

**Comment by DailyDreaming** [comment]
Closed via: https://github.com/HumanCellAtlas/data-store/pull/1958
