### ISSUE TITLE
Use a project uuid to download nested bundle files

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/dcp-cli#209]
I would like to download all the metadata files for a whole project without having to use other tools to first compile a list of bundles in the project then use this cli to download one bundle at a time.

I can see the use case of downloading data files or metadata and data files too but this wasn't my use case at the moment.

**Comment by mckinsel** [comment]
Do projects have a uuid in the metadata?

**Comment by sampierson** [comment]
Yes they do.

**Comment by kozbo** [comment]
There is a work around so this is low priority. Saying no for now.
