### ISSUE TITLE
CLI Help Menu Formatting

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/dcp-cli#219]
As a user of the CLI I would like to quickly look over the help menus for commands to get more information about the command that will be ran. 

# Problem

Currently the CLI help menu is missing information about what input the commands can utilize, this includes information about required/optional parameters, expected formatting for certain parameters.

This causes issues with having to branch off and find scattered information through READMEs or on swagger API pages.

# Reproduction 

```
 [venv-data-store]amar:~/dev/testing/hca-cli! hca dss get-bundles-checkout -h 
usage: hca dss get-bundles-checkout [-h] --replica {aws,gcp} --checkout-job-id
                                    CHECKOUT_JOB_ID

Use this route with the `checkout_job_id` identifier returned by `POST
/bundles/{uuid}/checkout`.

optional arguments:
  -h, --help            show this help message and exit
  --replica {aws,gcp}   Replica to fetch from.
  --checkout-job-id CHECKOUT_JOB_ID
                        A RFC4122-compliant ID for the checkout job request.

[venv-data-store]amar:~/dev/testing/hca-cli! hca dss get-bundles-checkout
usage: hca dss get-bundles-checkout [-h] --replica {aws,gcp} --checkout-job-id
                                    CHECKOUT_JOB_ID
hca dss get-bundles-checkout: error: argument --replica is required

```
--replica is identified as an optional, then later as a requirement 

```
[venv-data-store]amar:~/dev/testing/hca-cli$ hca dss put-bundle -h
usage: hca dss put-bundle [-h] --version VERSION --replica {aws,gcp} --uuid
                          UUID --files FILES [FILES ...] --creator-uid
                          CREATOR_UID

Create a new version of a bundle with a given UUID. The list of file
UUID+versions to be included must be provided.

optional arguments:
  -h, --help            show this help message and exit
  --version VERSION     Timestamp of bundle creation in DSS_VERSION format.
  --replica {aws,gcp}   Replica to write to.
  --uuid UUID           A RFC4122-compliant ID for the bundle.
  --files FILES [FILES ...]
  --creator-uid CREATOR_UID
                        User ID who is creating this bundle.

```

`--files` does not have a description for how the input should be specified to the user.

**Comment by DailyDreaming** [comment]
I was just thinking of proposing making this a sphinx project, when Lo and Behold, I Gaze Upon It and It Is There.

https://github.com/HumanCellAtlas/dcp-cli/pull/146

No idea why there is no link in the readme.  I found it just guessing what the path ought to be: https://hca.readthedocs.io/en/latest/

Not sure if anyone maintains this or checks when the docs break.
