### ISSUE TITLE
parameter clarification in help menu

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/dcp-cli#221]
### Issue
The help menu has slightly confusing information for the following items in the help menu.

### Observed
put-bundle -- No format given for files ( formatting present in swagger/Models page) 
put-file - URL needs to be specified to a bucket (CLOUD URL currently) 
download -- specify file formats for users for --data-files/--metadata-files 

### Notes

These clarifications can assist end users with troubleshooting / location information in faster means.

**Comment by DailyDreaming** [comment]
Closed by DSS PR: https://github.com/HumanCellAtlas/data-store/pull/1930 .
