### ISSUE TITLE
`iterate` methods don't handle errors very well

### ISSUE THREAD

**Issue by mckinsel** [HumanCellAtlas/dcp-cli#222]
When using the python API, I often have to use a pattern that looks like this

```python
while True:
    try:
        # <something with the DSS>
        break
    except:
        continue
```

This is because requests to the DSS often fail for any number of reasons and succeed later on retry. But I don't think you can use such a pattern with `iterate`. So if you get, say, a random 504, you have to start all over again.

**Comment by kislyuk** [comment]
A representative error showing this issue:
```
Traceback (most recent call last):
  File "./fetch.py", line 65, in <module>
    print(len(list(dss.post_search.iterate(es_query={}, replica="aws"))))
  File "/usr/local/lib/python3.6/dist-packages/hca/util/__init__.py", line 183, in iterate
    page = self._request(kwargs, url=page.links["next"]["url"] if page else None)
  File "/usr/local/lib/python3.6/dist-packages/hca/util/__init__.py", line 149, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: unhandled_exception: sequence item 0: expected str instance, NoneType found (HTTP 500). Details:
Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/search.py", line 80, in post
    next_url = _build_next_url(page, per_page, replica_enum, output_format)
  File "/var/task/chalicelib/dss/api/search.py", line 150, in _build_next_url
    search_after = ','.join(page['hits']['hits'][-1]['sort'])
TypeError: sequence item 0: expected str instance, NoneType found
```
Here `dss` is an instance of `hca.dss.DSSClient()`.

I believe this is caused by the iterator internals not installing standard retry logic in pagination requests.

**Comment by kislyuk** [comment]
Digging into this a little bit deeper, I think this is not specific to the iterator, but is instead because we don't retry at all on 500 errors. Do we have a rationale why? We should probably go ahead and add all 500 series codes to hca.util.RetryPolicy.

**Comment by DailyDreaming** [comment]
See #267 .
