### ISSUE TITLE
Download bundle manifest as bundle.json

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/dcp-cli#231]
`hca dss download` and `hca dss download-manifest` do not include `bundle.json`
files in the download.  The `bundle.json` contains information not available in any of the downloaded metadata files and is key to understanding the bundle.

**Comment by hannes-ucsc** [comment]
To clarify, `bundle.json` is an arbitrary name that bears no significance in the metadata or the DSS. The DSS refers to this JSON structure as the *bundle manifest*. It *is* the object that represents a bundle in the DSS and that makes up the response of `GET /bundles/$uuid`.

It does make sense to store the bundle manifest in a file called `bundle.json` on the user's disk. To fit into the `.hca` cache implemented in #234, the primary location of this file should be `.hca/bundles/$bundle_fqid` with a user-friendly hardlink in `$bundle_fqid/bundle.json`

**Comment by theathorn** [comment]
@jessebrennan to evaluate potential bug with implementation and raise isssue.

**Comment by theathorn** [comment]
@jahilton  automation is not required for General Availability. Removing from epic.

**Comment by jessebrennan** [comment]
This needs to be released.
