### ISSUE TITLE
Reorganize file structure created by CLI  download

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-cli#233]

**Comment by kozbo** [comment]
Integrate with Orange to build metdata.tsv and metadata.json

**Comment by theathorn** [comment]
Suggested directory structure for download:

<$project>/<$sample>/<e.g. fastq file>

**Comment by hannes-ucsc** [comment]
Add `--layout bundle` (default) and `--layout sample` to `hca download-manifest`. Build on the hard-link feature from #234.

**Comment by diekhans** [comment]
How does:
   <$project>/<$sample>/<e.g. fastq file>
work with pooled samples?  

The experiment graph is a DAG, and scientists will make all kinds of interesting DAGs no one anticipated.

**Comment by hannes-ucsc** [comment]
The data file will be hard linked into each of the directories representing the specimens in the pool. Consider #237 for more discussion on the layout feature.

**Comment by hannes-ucsc** [comment]
Also see [#cli-download-layout](https://humancellatlas.slack.com/messages/CGC94QM1R) on Slack for discussion.

**Comment by theathorn** [comment]
See #355 for further download manifest improvements.
