### ISSUE TITLE
Download multiple files concurrently

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#236]
`hca dss download-bundle` and `hca dss download-manifest` should download multiple files in parallel using a thread pool of size, say, 5 * the number of cores.

**Comment by Bento007** [comment]
@hannes-ucsc the python binding would allow users to download multiple file concurrently. Is this sufficient?

**Comment by kozbo** [comment]
Please write up a use case and a definition of done for this ticket, use the issue template:

**Comment by hannes-ucsc** [comment]
@kozbo which template? AFAICT, there are no issue templates configured for this repository.

@Bento007, this ticket is about the CLI, not the bindings. I'll clarify that in the description.

To indicate that my team owns these tickets, I've assigned them to me. There is nothing the DSS team needs to do right now, but we would definitely like your help reviewing the PRs.

**Comment by kozbo** [comment]
Can we define an interface to allow this issue to be unblocked?

**Comment by hannes-ucsc** [comment]
Not easily possible and not much value in doing so as this is only a 2.
