### ISSUE TITLE
CLI should automatically check to see if there is a newer version available

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-cli#240]
## User story
* As a CLI user
* I want to know when my client code is out of date
* so that I don't get weird errors and discover problems that may cause unnecessary thrash

## Definition of done
Either the code checks every time a CLI command is run (what do we do if Pipy is off line?) or when you run the --version option.

**Comment by diekhans** [comment]
The pip command itself checks if there is a new version available and gives a warning.  If pypi is offline (rare) just skip the warning.

It is bad form for a command line tool to auto update.

Related, the hca refresh-swagger command seems rather a source of error.  Can't this happen automatically.  Why  should a user even have to know what swagger is?

**Comment by diekhans** [comment]
Does this including checking for swagger files needing updated?  That is part of the cli being out of date and is very confusing when it happens.   Plus having to know about swagger is adds to the cognitive load of understanding the CLI.

**Comment by DailyDreaming** [comment]
Fixed via #249.
