### ISSUE TITLE
Atomically and reliably create a `.version` for a download file store 

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#251]
The version file should contain the layout version and its parameters. This makes it possible to update the layout in the future. The file needs to be created if it doesn't exist and that's where the race conditions come in. These race conditions should be handled. Note that it's not sufficient to just create the file atomically because that would mean that last writer wins.

**Comment by jessebrennan** [comment]
We decided to implement this as a version directory which contains all of the files downloaded with that version.
