### ISSUE TITLE
Review log verbosity produced by file download from manifest

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/dcp-cli#255]
From @matthewspeir:
- A verbosity setting to hide warning/retry or other unnecessary messages would be great. Let me decide how much info I want to see or hide the details and put them in a log file.
- Basically I just want to know if it succeeded in downloading a file (and sometimes I don’t even care to see that.)

**Comment by Bento007** [comment]
```$ hca --help
usage: hca [-h] [--version] [--log-level {DEBUG,INFO,WARNING,CRITICAL,ERROR}]
           {help,upload,dss}
```
In practice it looks like
``hca --log-level INFO dss ...`

**Comment by amarjandu** [comment]
## Notes 4/8/19 : 9:20 AM

### Complete
Tested `--log-level {DEBUG,INFO,WARNING}` commands to see if they operate correctly.
`--log-level` works as expected, setting level to `INFO` prints out only bundle information as requested.
