### ISSUE TITLE
WARNING messages from the CLI

### ISSUE THREAD

**Issue by matthewspeir** [HumanCellAtlas/dcp-cli#256]
Talked to @hannes-ucsc and @NoopDog about this a bit already. Here are the WARNING messages I was seeing. I think the messages were just a little bit overwhelming at first and that's what threw me off. 

![hcaclierrormessages](https://user-images.githubusercontent.com/11509990/53771700-80e5b680-3e98-11e9-9ce9-7a66e811686d.png)

**Comment by hannes-ucsc** [comment]
Those messages shouldn't even be logged at WARNING level. The 301s that trigger them are benign, expected and are by no means a sign of something bad going on. Looks like @Bento007 added this as part of https://github.com/HumanCellAtlas/dcp-cli/pull/216. We should not log retries triggered by redirects at WARNING level.

**Comment by Bento007** [comment]
I'll fix it
