### ISSUE TITLE
non-interactive login fails

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/dcp-cli#258]
```
hca dss login
Please visit this URL to authorize this application: https://auth.dev.data.humancellatlas.org/authorize?response_type=code&client_id=qtMgNk9fqVeclLtZl6WkbdJ59dP3WeAt&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=openid+email+offline_access&state=gdTQGtfyzkBBUN4xnwBeern5OKmWgh&audience=https%3A%2F%2Fdev.data.humancellatlas.org%2F&access_type=offline
```

![image](https://user-images.githubusercontent.com/32105697/53827338-ac67b000-3f2f-11e9-875b-4d4c8a6ee17e.png)

# Details
We are using the google_auth_oauthlib server flow to Login users https://github.com/HumanCellAtlas/dcp-cli/blob/6f67cd8808582488bd198e6ed61235332a5a597a/hca/util/__init__.py#L363

the remote machine create server at its localhost:8080 and uses the users local browser to login. Auth0 expects to return the code to localhost:8080 from the browser, but since the local machine does not have localhost:8080 open, the transactions fails.

### Solution 1
Send the code directly to the server using the servers full address, but auth0 uses a white list of allowed callback this prevents this solution since we cannot account for all possible addresses to allow.

**Comment by Bento007** [comment]
this is the expected behavior. For non-interactive login you need Google service credentials.

**Comment by Bento007** [comment]
auth0 does not support urn:ietf:wg:oauth:2.0:oob to echo the return the code to the browser.

**Comment by Bento007** [comment]
hitting `https://auth.data.humancellatlas.org/login?state=ABC&redirect_uri=https://auth.dev.data.humancellatlas.org/echo` will allow users to login and echo the token to the browser. This could be used to return the token to the user so they can copy it to the remote server.
