### ISSUE TITLE
Test DCP-CLI with Python 3.7

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/dcp-cli#259]
## User Story
As a DSS CLI user that keeps my system up to date with the latest Python version, I want the DSS CLI to work with Python 3.7

Note: I have not tried running the DCP CLI using Python 3.7, it may or may not work properly.
I'll estimate the story points at 2 for setting-up GitLab dcp-cli CI to include Python 3.7, and if significant issues are found, additional tickets can be opened to resolve them.

## Done When
The DCP CLI is tested with Python 3.7 as part of standard CI, and all tests pass successfully.

**Comment by theathorn** [comment]
@hannes-ucsc interested in hearing an update on this.
