### ISSUE TITLE
Bug on Mac: help screen diversion

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/dcp-cli#279]
CLI issue raised by a user Robert Petryszak. Ticket moved from conversation on slack with @DailyDreaming and @amarjandu

**Problem: CLI not working on mac**

Running:
`hca dss download --bundle-uuid 2aa60809-108b-4541-85f9-0beda04280e9 --replica aws --data-files "SRR3563227_1.fastq.gz" --metadata-files ""`

Help screen output rather than the expected download. The help screen is being output due to the following code:

if sys.version_info >= (2, 7, 9):  # See https://bugs.python.org/issue9351                                                                                                                                                                              
        dss_parser.set_defaults(entry_point=help)

in hca/dss/cli.py

My sys.version.info is:
"major=3, minor=7, micro=2, releaselevel='final', serial=0" <sys.version_info>
as I assume it’s yours - given 'hca 4.8.0 (CPython 3.7.0 Darwin-18.2.0-x86_64-i386-64bit)’ you showed me before.

- Tried fresh virtualenv install.

**Comment by DailyDreaming** [comment]
I don't run Mac, but can confirm this doesn't seem to be an issue on Ubuntu.  Maybe @amarjandu (mac user) has insight?

**Comment by hewgreen** [comment]
This isn't an issue for me on my mac either. Robert and I have the same version of the client installed.

**Comment by kozbo** [comment]
I just checked on both Python 2.7 and 3.64 on my Mac, both worked for me

**Comment by amarjandu** [comment]
@hewgreen could run `﻿git show --oneline -s` when within the directory of the dcp-cli? I also assume that your version of the dcp-cli is 4.8.0?

**Comment by hewgreen** [comment]
I can't recreate the problem. I think @rpetry needs to run this. I have sent him this ticket so he will comment shortly.

**Comment by DailyDreaming** [comment]
Reposting the installation from source instructions here, just for reference:
`git clone https://github.com/HumanCellAtlas/dcp-cli.git`
`cd dcp-cli`
`virtualenv -p python3.6 v3nv`
`. v3nv/bin/activate`
`pip install wheel`
`pip install -r requirements-dev.txt`
`make install`

**Comment by datasome** [comment]
@DailyDreaming, I follow the above installation instructions to the letter, and inside (v3nv) the following example call still gives me the help screen:
hca dss download --bundle-uuid ffbcaded-fc09-41c9-85ae-357c66e497d1 --replica aws --metadata-files "" --data-files "ERR2457575_1.fastq.gz"

Also, inside cloned dcp-cli, git show --oneline -s
faa00ac (HEAD -> master, origin/master, origin/HEAD) Parellelize downloads for manifest (fixes #236)

**Comment by amarjandu** [comment]
@datasome I attempted to replicate this issue by creating a clean test environment, following the posted instructions above, and using the example, but i dont see the help menu, im able to get the download of the fastq file.

I assume that any modifications to the code that was being tested with Matt Green was reverted back to the original code?
If not performing the command: `git reset -- hard` will revert any changes made to the codebase.

We are also available on [Slack](https://join-hca-slack.herokuapp.com/) perhaps it might be easier to communicate on there / share images / conference call. There might be some troubleshooting with pip/python that needs to be looked at.

**Comment by DailyDreaming** [comment]
@datasome I'll let Amar handle this one since he's an actual mac user.

**Comment by amarjandu** [comment]
Moved conversation to Slack, will post resolution back to Github Issues

**Comment by amarjandu** [comment]
# Issue Resolved
## Bug Source: 
custom python path was placing the site-package
in at the top of the sys.path, this replaced the import for argparse
within the `hca/cli.py`. The sub-parsing mechanism does not work
as we expect it to. Need to keep the default version of argparse that 
python ships with and not the dependency that is installed from pypi.
# Steps Required:
Need to move any `/site-package` to the end of the list for `sys.path` 
This might want to be done within the `hca/cli.py` folder so the user
does not have to adjust their pythonpaths for each shell instance. 
# Notes:
Problematic sys.path, issue with with second element.
```
['/Users/rpetry/Documents/misc/python3/temp/dcp-cli/v3nv/bin', '/Users/rpetry/Documents/misc/python3/temp/dcp-cli/v3nv/lib/python3.6/site-packages', '/Users/rpetry/Documents/misc/python3/temp/dcp-cli/v3nv/lib/python36.zip', '/Users/rpetry/Documents/misc/python3/temp/dcp-cli/v3nv/lib/python3.6', '/Users/rpetry/Documents/misc/python3/temp/dcp-cli/v3nv/lib/python3.6/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6']
```

**Comment by amarjandu** [comment]
@DailyDreaming i think we should leave this open until a patch is placed, see `Steps Required`

if SOP is something else, please close.

**Comment by DailyDreaming** [comment]
I don't think we should be adjusting python paths for users as a part of the installation.  This can open up a whole new host of problems and is highly dependent on their system.

One solution could be explicitly setting the `argparse` version in the `requirements.txt` if that was the problem.

**Comment by amarjandu** [comment]
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH 
If looking at a solution for this, i would propose adjusting the `sys.path` to move any references of the `/site-package` to the last entry of the list. 
This would permit the PATH modification to be scoped for the process of the cli. and will place built-in libraries at a higher priority. 
The dependency [arg-parse](https://pypi.org/project/argparse/) has not been updated since 2015, i believe we get the most current version, which does not have good sub-parser support.

**Comment by DailyDreaming** [comment]
So, the other solution to fixing this is to delete the package installed that was causing the problem and then install the correct package.

Massaging the order of things in `sys.path` means guessing where the user keeps "The Correct" packages, which depends a lot on their environment.  I'm not sure that that's the right approach.
