### ISSUE TITLE
`download` parallelization higher than available pool connections

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/dcp-cli#312]
```
INFO:hca:Retrying: RequestHistory(method='GET', url='/v1/files/2d64aa4f-004a-4899-bdc8-a46e3c2bef96?version=2019-04-20T190034.277283Z&replica=aws', error=None, status=301, redirect_location='https://dss.dev.data.humancellatlas.org/v1/files/2d64aa4f-004a-4899-bdc8-a46e3c2bef96?replica=aws&version=2019-04-20T190034.277283Z&token=%7B%22execution_id%22%3A+%2255abb75d-ba28-4b78-bf4f-8315b7744e2d%22%2C+%22start_time%22%3A+1555786887.3318763%2C+%22attempts%22%3A+0%7D')
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: dss.dev.data.humancellatlas.org
INFO:hca:Download 'sequence_file_1.json' to '.hca/v2/files_2_4/0e/48fd/0e48fdc80be7d661268c38383f770cfdeaa9978d8670a9231ae9950669811b85'.
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: dss.dev.data.humancellatlas.org
INFO:hca:Download 'process_1.json' to '.hca/v2/files_2_4/24/ea2c/24ea2c4257aa029c4e1f7dff31138a5e668a951384ceb344c05f10f8fc564b6e'.
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: dss.dev.data.humancellatlas.org
INFO:hca:Download 'project_0.json' to '.hca/v2/files_2_4/2f/6350/2f6350d90363747ba464f1b6bdfce7c6c0a5983941f349e53a330990dd2c1440'.
INFO:hca:Download 'sequencing_protocol_0.json' to '.hca/v2/files_2_4/1c/bba5/1cbba5403b47877e3d81dcfc9b61dc029de65ddc532f3170d8bd1568b27d0839'.
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: dss.dev.data.humancellatlas.org
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: dss.dev.data.humancellatlas.org
```

This hinders connection re-use, reducing the benefit of parallelized downloads.

**Comment by barkasn** [comment]
I see the same problem and it's preventing me from downloading datasets. Here is the python error:

$ hca dss download-manifest --manifest hca-manifest-9bfe77d2-4cf0-46b8-b588-47dbac3bc63b.tsv --replica aws
[...]
INFO:hca:Download 'SRR6259682.fastq.gz' to '.hca/v2/files_2_4/bc/bb24/bcbb24677f730319aba7c29355d158f34be8b96bc263cf30b84e02c60426ea67'.
INFO:hca:Download 'SRR6259289.fastq.gz' to '.hca/v2/files_2_4/1f/9125/1f9125071f4bb270967f82a3faf05d87af43e87b29980fbd11bef691957d1a01'.
INFO:hca:Download 'SRR6259963.fastq.gz' to '.hca/v2/files_2_4/f9/a5e1/f9a5e1fb44e8fcad839f5290bfb85a309e9c07af82481c5684bb421755c74c57'.
INFO:hca:Download 'SRR6258240.fastq.gz' to '.hca/v2/files_2_4/49/94d5/4994d55acff507813c41972e7b397126b1499b5ea0e0753b33ec10ec023e1fda'.
INFO:hca:Download 'SRR6259455.fastq.gz' to '.hca/v2/files_2_4/b2/392c/b2392ca1d0f8278f97f49ff7730743f1352cfb4eb98702d0990766cb7a6eb769'.
INFO:hca:Download 'SRR6259262.fastq.gz' to '.hca/v2/files_2_4/ff/327e/ff327ec2145e31e10562206869c9f990d579d8c82efc76fbd00dd79befc46c6f'.
INFO:hca:Download 'SRR6259666.fastq.gz' to '.hca/v2/files_2_4/d2/f876/d2f876798336b0c76f91b0808add8abb4a37ef074b283671b14010c383b3ebdb'.
INFO:hca:Download 'SRR6258848.fastq.gz' to '.hca/v2/files_2_4/0a/c539/0ac539e8d856c812525e4a71a96fddd607af5993a5a1f97aab906bd53975d62d'.
INFO:hca:Download 'SRR6259845.fastq.gz' to '.hca/v2/files_2_4/8b/9fb5/8b9fb55b8d597292630571715e6a7e1bc81d07737c61e6749ea6b84709c7f271'.
INFO:hca:Download 'SRR6259453.fastq.gz' to '.hca/v2/files_2_4/ee/74cc/ee74cc1385bad86b5736cfd061073051308dd932e79fb0a406b1cbcf816fa772'.
INFO:hca:Download 'SRR6259075.fastq.gz' to '.hca/v2/files_2_4/02/5af9/025af95c3e103035514ce7901a21c0361e377a8b1d92a588dad120a7fff3ebd9'.
INFO:hca:Download 'SRR6257943.fastq.gz' to '.hca/v2/files_2_4/59/911d/59911d91a356b52123b2b69e138be76505ff04e9a8659b2d723853202f7eeb8b'.
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: org-hca-dss-checkout-prod.s3.amazonaws.com
INFO:hca:Download 'SRR6258533.fastq.gz' to '.hca/v2/files_2_4/40/6687/406687deb947bf93433462c4b81502fab785e91bb475da3b574f534d0816b7de'.
Traceback (most recent call last):
  File "/home/nbarkas/hcacli_venv/bin/hca", line 10, in <module>
    sys.exit(main())
  File "/home/nbarkas/hcacli_venv/local/lib/python2.7/site-packages/hca/cli.py", line 131, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/nbarkas/hcacli_venv/local/lib/python2.7/site-packages/hca/util/__init__.py", line 544, in arg_forwarder
    return command(**command_args)
  File "/home/nbarkas/hcacli_venv/local/lib/python2.7/site-packages/hca/dss/__init__.py", line 454, in download_manifest
    raise RuntimeError(bundle_error_str + (' and ' if bundle_errors and file_errors else '') + file_error_str)
RuntimeError: 2 file(s) failed to download
