### ISSUE TITLE
Using get_bundle.iterate makes it impossible to get the bundle version

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#331]
When I call `client.get_bundle.iterate(…, version=None, …)` I am supposed to get the latest version of the bundle back. The only way to determine what the actual `version` value is, I should be able to use `bundle.version` from the response. However, the `.iterate()` method only exposes only `bundle.files` so I would have to make another round-trip to `client.get_bundle()` (without `.iterate()`) to get to that. That's 1) racy (the latest version might change) and 2) inconvenient.

Regression from the fix for #253.

**Comment by DailyDreaming** [comment]
@hannes-ucsc Using this should avoid the race:
```
bundle.version = client.get_bundle()
for file in client.get_bundle.iterate(…, version=bundle.version, …)
    do something cool
```
Does that work for your use-case?

**Comment by hannes-ucsc** [comment]
> Does that work for your use-case?

As a workaround, yes, but fetching the first page twice is inefficient and a bit cumbersome for our customers. 

I would fix this by having the iterator return entire pages instead of specific elements in each page. This would make that iterator more generic because you wouldn't need to assume anymore that `GET /bundle` has `bundle.files` or that `GET /collection` has `collection.items` or that `POST /search` has `results`.

**Comment by hannes-ucsc** [comment]
Alternatively,  the iterator could have additional attributes. So you could do 

```
response = client.get_bundle.iterate(…)
version = response.json['version']
for file in response:
    do something cool
```

**Comment by DailyDreaming** [comment]
@hannes-ucsc I agree it would be nice and more generic if it were just a list and there were no keywords.  That seems like a breaking change to the API though, and I'm not sure if I can do that?

Adding an additonal attribute like json seems like it might double the payload of the response data if I'm understanding you correctly?

Andrey made a comment today about the keywords too: https://github.com/HumanCellAtlas/dcp-cli/commit/a84fae932fe96770a88501aeae9eb31d40ff2785

I'll make a PR eliminating them, and then flag you both for comment.  Any change to the swagger yml will be slow though, as it has to propagate through all of the stages before code can be made in the CLI to ingest it.

**Comment by xbrianh** [comment]
Note that bundle version is available in the paged response `Link` header, so it's possible to pull it into CLI iteration.

Whether this is an acceptable solution is another question. What do you think @hannes-ucsc and @kislyuk?

**Comment by hannes-ucsc** [comment]
>  I agree it would be nice and more generic if it were just a list of full pages. That seems like a breaking change to the API though, and I'm wary of breaking changes.

But https://github.com/HumanCellAtlas/data-store/pull/2104 is breaking backwards compatibility. That seems inconsistent with your statement above. Anyhow, we are not GA yet so we CAN make backwards-incompatible changes. We just need to communicate them well and make them for good reasons.

> I like your proposed solution

I actually prefer my the first solution of having the iterator yield full pages.

> and I could definitely add a json method to the pagination method

I'm proposing a `.json` attribute, not a method. 

Since you are willing to break backwards compatibility in the DSS, why not fix iterate() in the most intuitive way? `.json` is ok but it is easy to miss and kinda hacky. If you are really worried about compatibility you could add `.iterate_pages()` and leave `.iterate()` in place.

> Note that bundle version is available in the paged response Link header, so it's possible to pull it into CLI iteration.

It's also in the response body where it is easier to extract. In the future, there may be other response elements that iterate() makes inaccessible. That's why I am proposing to have iterate return the full response and not just the element that contains the list of child elements (files, collection items, search results etc).

**Comment by kislyuk** [comment]
@hannes-ucsc I like your approach and reasoning. May I suggest a slight change: leave `.iterate()` as is, and introduce `.paginate()` that will yield full page documents? We can then also fix up the docs to clarify the difference between pagination and iteration.

**Comment by kislyuk** [comment]
(To clarify - I don't want to let go of what is to me the main advantage of `.iterate()` yielding actual array elements - the reduction of boilerplate in the library client. If iterate returns full pages, the client has to have a nested loop or accessory iterator.)

**Comment by xbrianh** [comment]
Is providing both `.paginate` and `.iterate` less confusing than assigning the non-iterated response elements as attributes on the object returned by `.iterate`?

Riffing off the suggestion from Hannes, why can't we have this:
```
response = client.get_bundle.iterate(…)
version = response.version
for file in response:
    do something cool
```

**Comment by kislyuk** [comment]
@xbrianh currently, `iterate()` is a coroutine. All response state is carried in the coroutine scope. The change proposed by you and in the current form of #334 would convert it into an object that implements the iterator protocol (`__iter__()`). Carrying response state around in that object, and exposing it through attributes, can be confusing because either it won't be available and instantiated until the first page of results is fetched in iteration, or the first page fetch will immediately trigger before iteration; also, the attribute values may change as the iterator transitions from page to page.

**Comment by DailyDreaming** [comment]
@kislyuk @hannes-ucsc Code is easier.  Please have a look at #335 .  I think it should do what you want.

**Comment by hannes-ucsc** [comment]
@kislyuk +1 on `.paginate()` and `.iterate()`
