### ISSUE TITLE
Release 6.0 with `download-manifest --layout` changes

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#333]
#297 adds `--layout` to `download-manifest` which default to `none`.  This creates only the `.hca` file store and a rewritten manifest in the current working directory. Orange thinks that this should be the default behavior. The previous behavior is accessible as `--layout `bundle`. Because this breaks backwards compatibility, we should bump the major version.

**Comment by hannes-ucsc** [comment]
Ping @briandoconnor when this is done so he can test it.

**Comment by jessebrennan** [comment]
@briandoconnor this has been released as 6.0.1 and is ready for you to test.

**Comment by hannes-ucsc** [comment]
Demo-ed on 5/13/2019
