### ISSUE TITLE
DSS API Testing and Tutorials

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/dcp-cli#362]
Test all CLI endpoints.
Create issues if you get confusing errors or commands don't work as expected.

For each 
 - Test the Endpoint.
 - Explain anything that was confusing (example: if you didn't know what a uuid was or how to generate or use one, include a better explanation of it in the PR).
 -  (API) Create a Working Code Example (https://hca.readthedocs.io/en/latest/api.html).
 -  (CLI) Create a Working Code Example (https://hca.readthedocs.io/en/latest/cli.html).
 -  Make the Example a Unit Test (similar to what was done for toil: https://github.com/DataBiosphere/toil/blob/master/src/toil/test/docs/scriptsTest.py).

AND
- make sure that all documentation endpoints are correct, including the Swagger, RTD, and CLI help.

Prioritize the read endpoints over the write endpoints 

**get-bundles-checkout**
**delete-bundle**
**get-bundle**
**patch-bundle**
**put-bundle**
**post-bundles-checkout**
**get-collections**
**put-collection**
**delete-collection**
**get-collection**
**patch-collection**
**get-file**
**head-file**
**put-file**
**post-search**
**get-subscriptions**
**put-subscription**
**delete-subscription**
**get-subscription**
**login**
**logout**
**refresh-swagger**
**upload**
**download**
**download-manifest**
**create-version**

**Comment by chmreid** [comment]
Tutorial scripts are written and tested, but PR #424 (to add tutorials) was never finished or merged into master. This PR was closed and continued by #472, which will close this issue.
