### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/dcp-cli#409]
_“DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won’t be maintained after that date. A future version of pip will drop support for Python 2.7.“_

The Tech Arch team has approved dropping Python 2.7 support.

Please note that `dcplib`, on which dcp-cli depends, is dropping support for Python 2.7 after version 2.1.2.

**Comment by theathorn** [comment]
Isn't this done?
