### ISSUE TITLE
Simplify client API.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/dcp-cli#410]
It would be nice if instead of this:

```
from hca import HCAConfig
from hca.dss import DSSClient

hca_config = HCAConfig()
hca_config["DSSClient"].swagger_url = f"https://dss.data.humancellatlas.org/v1/swagger.json"
dss = DSSClient(config=hca_config)
```

Users could just call:

```
from hca.dss import DSSClient

dss = DSSClient()
```

And the API would default to `prod`.  The only reason to set the json is if one is a developer.  Otherwise, normal users should be able to call a client and have it default appropriately.

**Comment by kislyuk** [comment]
This is already the default behavior (see https://github.com/HumanCellAtlas/dcp-cli/blob/master/hca/default_config.json). Please check your `~/.config/hca/config.json`.
