### ISSUE TITLE
download-manifest downloads fastq files twice for analysed projects?

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/dcp-cli#450]
I was playing around with downloading files using the `hca dss download-manifest` command and I discovered that when a dataset has been analysed, the fastq files are listed in both the primary and secondary bundles. This causes there to be two lines in the manifest file for the same file. As you are downloading it lists the file as being downloaded twice to the same location which I thought was a bit odd.

```
...
INFO:hca:Download 'Retina_Wong_scRNA_Sample5_I1.fastq.gz' to './double/.hca/v2/files_2_4/cc/6bf0/cc6bf034743ed5bf781320deeceb119b4584a7854d922b59f05392d6cd5cc737'.
INFO:hca:Download 'Retina_Wong_scRNA_Sample5_I1.fastq.gz' to './double/.hca/v2/files_2_4/cc/6bf0/cc6bf034743ed5bf781320deeceb119b4584a7854d922b59f05392d6cd5cc737'.
```

I made a trivial example where I made a tsv manifest with a single file listed and one with a double and compared the run time as well as the size taken up on disk.

When I ran the download with a single fastq file it took 50s, when I ran with two files that are  the same file it took 82s.

When I checked the size of the .hca folder that is downloaded
``` 
(beta_venv) C02YV4HKLVDL:test_dup_download mshadbolt$ du -sh double/
1.6G	double/
(beta_venv) C02YV4HKLVDL:test_dup_download mshadbolt$ du -sh double/.hca
818M	double/.hca
```
But I don't think this is accurate because it double counts when there are hard links I think.

```
(beta_venv) C02YV4HKLVDL:1bfb3f90-6451-4084-a629-00cbc80c3592.2019-09-13T091553.823908Z mshadbolt$ ls -li
total 1655984
(beta_venv) C02YV4HKLVDL:double mshadbolt$ ls -il double/1bfb3f90-6451-4084-a629-00cbc80c3592.2019-09-13T091553.823908Z/
total 1662872
7108801 -rw-------  1 mshadbolt  EBI\Domain Users  847438091 27 Sep 16:21 Retina_Wong_scRNA_Sample5_I1.fastq.gz

(beta_venv) C02YV4HKLVDL:double mshadbolt$ ls -il double/bdb0032a-180d-4810-9f07-3d7e46f2ea19.2019-09-14T035851.501822Z/
total 1675208
7108755 -rw-------  2 mshadbolt  EBI\Domain Users  847438091 27 Sep 16:21 Retina_Wong_scRNA_Sample5_I1.fastq.gz
```
Looking at the inode numbers in the 'double' test I can see that the fastq files are both pointing to the different inodes, indicating they aren't hard-linked (i think?). I am wondering whether the file is downloading twice to the same directory and that is why it is taking almost double the amount of time?

I have attached some of the files that I used for my tests with the manifests and bash script I used

[test_files.zip](https://github.com/HumanCellAtlas/dcp-cli/files/3663352/test_files.zip)

As a side note I'd like to know why we force users to download a bunch of json files when they only requested a fastq...

**Comment by theathorn** [comment]
@jessebrennan to triage.

**Comment by jessebrennan** [comment]
Thanks @mshadbolt for this thorough issue report. I'll try and reproduce.

In regards to:

> As a side note I'd like to know why we force users to download a bunch of json files when they only requested a fastq...

If you run
```
hca dss download --help
```
you will see
> By default, all data and metadata files are downloaded.

The docs are not quite accurate here for disabling the download; `--no-metadata` is the option you were looking for. This was at one point the only way for a user to get at the bundle metadata, which I think is why it was always downloaded like this.

If you think metadata should not be downloaded by default, then we should probably make a separate issue and get some input from UX people.

**Comment by jessebrennan** [comment]
So this is causes by a race condition in the download code.

- both files are downloading simultaneously
- one finishes first and links from the bundle dir to the filestore
- the second finishes downloading to the filestore, overwriting the first entry in the filestore

Now the first downloaded copy is still linked by the bundle dir and has a different inode from the file in the filestore, thus doubling the space consumption, etc.

The resolution may be as simple as changing https://github.com/HumanCellAtlas/dcp-cli/blob/master/hca/dss/__init__.py#L527 to `overwrite=False`, although there could be some complications using this option on Windows.

Thanks @mshadbolt for finding this bug!

**Comment by mshadbolt** [comment]
Thanks for following up, glad to help improve the user experience :)

With regards to the metadata json files, I think that users should be able to explicitly choose to download the metadata and in the format they would like by specifying it in a similar way they can choose to download bam or fastq files. But as a user if I create a manifest where I specified that I wanted to download fastq files I wouldn't expect to also get 200 json files. I can't imagine any downstream user being able to figure out how to use the json files that we give them but agree that this needs to be investigated more in terms of what is best for the user and what format they would like to see. 

One step forward could be allow downloading the metadata tsv through the manifest as well since this is the most useable metadata we have at the moment (even though it is still rather difficult to use and understand). Not sure if it is possible as this is something created outside of the DSS I believe? I find it kind of annoying that at the moment if you want the metadata tsv from more than one project you have to download each one individually by clicking all the buttons in the browser. But anyways just thinking out loud.

**Comment by jessebrennan** [comment]
@hannes-ucsc asked to set this estimate to 5.

**Comment by hannes-ucsc** [comment]
@mshadbolt 

> Not sure if it is possible as this is something created outside of the DSS I believe?

Yes, Azul creates it more or less on the fly when you request it.

> I find it kind of annoying that at the moment if you want the metadata tsv from more than one project you have to download each one individually by clicking all the buttons in the browser

Agreed, this is a UI limitation. Azul already has the ability create a manifest for everything, or any subset of everything. I filed https://github.com/HumanCellAtlas/data-browser/issues/912.

> this needs to be investigated more in terms of what is best for the user and what format they would like to see

@jessebrennan and I discussed a few alternatives and create a poll on Slack:

https://humancellatlas.slack.com/archives/C51A8EDQQ/p1570066762027000
