### ISSUE TITLE
Pen-test build infrastructure

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#508]
Specifics to be discussed on Slack.

**Comment by theathorn** [comment]
@hannes-ucsc wrote:

Verify two things:
1) PRs filed against the DCP CLI from a fork do not have access to the secret environment variables that would allow Travis to decrypt encrypted files in the source tree, therefore gaining escalated privileges to access to cloud resources, like being able to create bundles in any DSS deployment.
2) Travis or the AllSpark dev instance cannot modify any prod HCA resources, create DSS bundles, upload files, create subscriptions, any modifications.

@kozbo I propose that we ask someone on Redwood to address any possible security issues that the Boardwalk engineer uncovers.
