### ISSUE TITLE
Regenerate and release CLI to be consistent with API changes for October demo

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/dcp-cli#53]
Adding replica-specific search (aws, gcp) required the addition of the "replica" parameter to the search API. The CLI and python bindings need to be updated and released to make these changes available to our users.
There is also a data-store change under review that changes whether "replica" is a required parameter for some of the other API operations as well, and the  CLI and python bindings should be updated to reflect this change as well for the October demo.

**Comment by ttung** [comment]
Released 0.11.0 with support for async copy.
