### ISSUE TITLE
Add delete functionality to the CLI

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/dcp-cli#80]
## User story
As a user of the DCP CLI, I want to have access to the bundle deletion functionality in the data store project so that I can delete bundles.

Depends on https://github.com/HumanCellAtlas/data-store/pull/684

## Context
The `/bundles/{uuid}` HTTP endpoint in `data-store` now supports the HTTP DELETE method. This method requires the `replica` to be specified in the query string.

* Triggering this without a version deletes the whole bundle
* Triggering this with the version deletes that specific version

**Comment by kozbo** [comment]
Will this command be visible and accessible to all users of the CLI? Should we restrict it somehow?

**Comment by hannes-ucsc** [comment]
Good question, @kozbo. Until we have proper auth, the command could rely on boto credentials being present.

**Comment by hannes-ucsc** [comment]
… and invoke the deletion lambda directly through the AWS APIs. Same could be done for reindexing.

**Comment by kozbo** [comment]
Isn't this done?
