### ISSUE TITLE
python requests library not suitable for bulk data transfers

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/dcp-cli#99]
[requests](https://github.com/requests/requests/) is not suitable for bulk data transfers.

1. The only timeouts that can be specified are read and connect.  When the client is sending data, it needs to specify write timeout.  If we only specify read timeout, we have to guess how long it'll take to transfer the data, as the server won't respond until the upload is complete.
2. When using streaming requests, timeouts are _not_ observed at all.  That means if we have a network flap, the dcp cli will hang indefinitely.

[pycurl](http://pycurl.io/) might be a solution, or maybe just switching to one of the urllib flavors.

**Comment by kislyuk** [comment]
I think the timeout argument is passed down and set on the socket using settimeout (https://docs.python.org/3.6/library/socket.html#socket.socket.settimeout). If I understand correctly, that value applies to both read and write operations.

I think the socket timeouts should apply when streaming as well, but I'm trying to figure out the full implications of the streaming code path. Which code path are you looking at?

**Comment by ttung** [comment]
Hm... let me recheck the code for my experiments.  Maybe I'm doing something wrong.
